const MIN_LABEL_GROUP_SIZE = 8;
const MAX_LABEL_GROUP_SIZE = 16;


const DEFAULT_STUDENT_NAME = 'Имя';
const DEFAULT_STUDENT_SURNAME = 'Фамилия';

export { MIN_LABEL_GROUP_SIZE, MAX_LABEL_GROUP_SIZE, DEFAULT_STUDENT_NAME, DEFAULT_STUDENT_SURNAME }