titlePage:
    path: /
    controller: App\Controller\TeacherController::titlePage

loginPage:
    path: /login
    controller: App\Controller\TeacherController::loginPage

createTeacherApi:
    path: api/v1/teacher/create
    controller: App\Controller\TeacherController::createTeacherApi
