titlePage:
    path: /
    controller: App\Controller\TeacherController::titlePage

loginPage:
    path: /login
    controller: App\Controller\TeacherController::loginPage

createTeacherApi:
    path: api/v1/teacher/create
    controller: App\Controller\TeacherController::createTeacherApi

authorizeApi:
    path: api/v1/authorize
    controller: App\Controller\TeacherController::authorizeApi

onboardingPage:
    path: /onboarding
    controller: App\Controller\TeacherController::onboardingPage

groupsListPage:
    path: /groups/list
    controller: App\Controller\GroupsListController::groupsListPage

editGroupPage:
    path: /groups/edit
    controller: App\Controller\EditGroupController::editGroupPage

createGroupApi:
    path: /api/v1/group/create
    controller: App\Controller\GroupController::createGroupApi

deleteGroupsApi:
    path: /api/v1/group/delete
    controller: App\Controller\GroupController::deleteGroupsApi

changeGroupTitleApi:
    path: /api/v1/group/title/change
    controller: App\Controller\GroupController::changeGroupTitleApi

changeGroupSubjectApi:
    path: /api/v1/group/subject/change
    controller: App\Controller\GroupController::changeGroupSubjectApi