## Pages routes

titlePage:
    path: /
    controller: App\Controller\TeacherController::titlePage

loginPage:
    path: /login
    controller: App\Controller\TeacherController::loginPage

onboardingPage:
    path: /onboarding
    controller: App\Controller\TeacherController::onboardingPage

groupsListPage:
    path: /groups/list
    controller: App\Controller\GroupsListController::groupsListPage

editGroupPage:
    path: /groups/edit
    controller: App\Controller\EditGroupController::editGroupPage

# Page data API routes

editGroupPageApi:
    path: /api/v1/groups/edit
    controller: App\Controller\EditGroupController::getEditGroupPageApi

groupsListPageApi:
    path: /api/v1/groups/get
    controller: App\Controller\GroupsListController::getGroupsListPageApi

# API routes

createTeacherApi:
    path: /api/v1/teacher/create
    controller: App\Controller\TeacherController::createTeacherApi

authorizeApi:
    path: /api/v1/authorize
    controller: App\Controller\TeacherController::authorizeApi

createGroupApi:
    path: /api/v1/group/create
    controller: App\Controller\GroupController::createGroupApi

deleteGroupsApi:
    path: /api/v1/group/delete
    controller: App\Controller\GroupController::deleteGroupsApi

changeGroupTitleApi:
    path: /api/v1/group/title/change
    controller: App\Controller\GroupController::changeGroupTitleApi

changeGroupSubjectApi:
    path: /api/v1/group/subject/change
    controller: App\Controller\GroupController::changeGroupSubjectApi

marksTablePage:
    path: /table
    controller: App\Controller\MarksTableController::marksTablePage

getGroupDataByIdApi:
    path: /api/v1/group/{groupId}
    controller: App\Controller\GroupController::getGroupDataByIdApi

createStudentApi:
    path: /api/v1/student/create
    controller: App\Controller\StudentController::createStudentApi